const productStore = require('../services/productStore');
const userStore = require('../services/userStore');

// @desc    Get all products with filtering & sorting, or real-time Gemini AI search
// @route   GET /api/products
const getProducts = async (req, res) => {
  try {
    const isAiSearch = req.query.aiSearch === 'true';
    const searchQuery = req.query.search ? req.query.search.trim() : '';
    let products = [];
    let isAiGenerated = false;

    // 1. Explicit AI Search requested
    if (isAiSearch && searchQuery.length > 1) {
      try {
        const llmService = require('../services/llmService');
        const discovered = await llmService.searchProductsWithGemini(searchQuery);
        if (discovered && discovered.length > 0) {
          products = discovered;
          isAiGenerated = true;
        }
      } catch (aiErr) {
        console.warn('[ProductController] Explicit AI search notice:', aiErr.message);
      }
    }

    // 2. Standard catalog search & filter if not already generated by explicit AI search
    if (!isAiGenerated) {
      products = await productStore.getAll(req.query);

      // If search query was provided and local catalog has 0 matches, automatically search live with Gemini!
      if (products.length === 0 && searchQuery.length > 1) {
        try {
          const llmService = require('../services/llmService');
          const discovered = await llmService.searchProductsWithGemini(searchQuery);
          if (discovered && discovered.length > 0) {
            products = discovered;
            isAiGenerated = true;
          }
        } catch (geminiErr) {
          console.warn('[ProductController] Gemini auto search fallback notice:', geminiErr.message);
        }
      }
    }

    res.status(200).json({
      success: true,
      count: products.length,
      isAiGenerated,
      searchQuery,
      products
    });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// @desc    Get single product by ID
// @route   GET /api/products/:id
const getProductById = async (req, res) => {
  try {
    const { id } = req.params;
    const product = await productStore.getById(id);

    if (!product) {
      return res.status(404).json({
        success: false,
        message: 'Product not found.'
      });
    }

    // If authenticated, record to recently viewed
    if (req.user && req.user.id) {
      await userStore.addRecentlyViewed(req.user.id, product.id);
    }

    res.status(200).json({
      success: true,
      product
    });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// @desc    Get all product categories
// @route   GET /api/products/meta/categories
const getCategories = async (req, res) => {
  try {
    const categories = await productStore.getCategories();
    res.status(200).json({ success: true, categories });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// @desc    Get brands (optionally filtered by category)
// @route   GET /api/products/meta/brands
const getBrands = async (req, res) => {
  try {
    const { category } = req.query;
    const brands = await productStore.getBrands(category);
    res.status(200).json({ success: true, brands });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// @desc    Get user's saved wishlist products
// @route   GET /api/products/user/saved
const getSavedProducts = async (req, res) => {
  try {
    const user = await userStore.findById(req.user.id);
    if (!user) return res.status(404).json({ success: false, message: 'User not found.' });

    const products = await productStore.getByIds(user.savedProducts || []);
    res.status(200).json({ success: true, count: products.length, products });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// @desc    Get user's recently viewed products
// @route   GET /api/products/user/recently-viewed
const getRecentlyViewed = async (req, res) => {
  try {
    const user = await userStore.findById(req.user.id);
    if (!user) return res.status(404).json({ success: false, message: 'User not found.' });

    const products = await productStore.getByIds(user.recentlyViewed || []);
    res.status(200).json({ success: true, count: products.length, products });
  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

module.exports = {
  getProducts,
  getProductById,
  getCategories,
  getBrands,
  getSavedProducts,
  getRecentlyViewed
};
